### ISSUE TITLE
Use Lombok library 

### ISSUE THREAD

**Issue by Raouf25** [osopromadze/Spring-Boot-Blog-REST-API#20]
** Lombok  **
Using [Lombok](https://projectlombok.org/),  you can reduce java boilerplate code ( getter,  setter, contractor ... )

As an example please check: https://www.baeldung.com/intro-to-project-lombok

**Comment by thien1710** [comment]
Hello sir!
I cannot how to give a comment. So can you explain for me about the api '/api/users/{username}/giveAdmin'.
I have already login with the Admin account and give the token for it.

![postman](https://user-images.githubusercontent.com/47551623/91836187-a3ff4b00-ec74-11ea-9fa8-90530bf7efc5.PNG)
![code](https://user-images.githubusercontent.com/47551623/91836204-aa8dc280-ec74-11ea-87a5-8f7a629c9a95.PNG)
 I get error at line 148. Can you explain for me.

I am sorry about this post. If you don't like it, i can remove it.

Thank you.

**Comment by osopromadze** [comment]
[FIX](21 )
