### ISSUE TITLE
Postman POST signup error: 415 Unsupported Media Type 

### ISSUE THREAD

**Issue by PlaceofYichen** [osopromadze/Spring-Boot-Blog-REST-API#46]
Hi, thanks for sharing! I'm using your project as a practice to RESTful API design. 

I had the following issue when I tried to do "POST	/api/auth/signup	Sign up". As the title describes, Postman gives me an error code 415 Unsupported Media Type. 
Please see screenshot:
![inq](https://user-images.githubusercontent.com/50237753/147185433-969bd429-d236-48aa-9ebb-f96d71ba4deb.png)

Do you have any suggestions on this issue? Thanks again!

**Comment by osopromadze** [comment]
Hi @PlaceofYichen, As I see you are sending as raw text in request body. You need to send it as json, choose from options in postman or set `Content-Type: application/json` in headers.

**Comment by PlaceofYichen** [comment]
Hi @osopromadze, thanks for the reply! I have another question: I couldn't access "GET /api/users/me" even after I signed up & signed in. (The same issue goes with "GET users/posts/etc.")

![signin](https://user-images.githubusercontent.com/50237753/147623996-c4858e90-da4f-4a25-a8ef-d66d624035d2.png)

![inq2](https://user-images.githubusercontent.com/50237753/147624000-56cc0d01-cf62-46cb-ba0f-3839491449de.png)

Is this supposed to work like what I did? Thanks for bearing with my naive questions!

**Comment by AbhishekAnand01** [comment]
After successfully login . For accessing secured endpoints you need to pass access token in request header.

![image](https://user-images.githubusercontent.com/39114448/207065081-7d52ecde-48a5-41d8-a566-4b636d6b1a56.png)

Hoping this will help you.
