### ISSUE TITLE
Postman GET error: 401 Unauthorized

### ISSUE THREAD

**Issue by PlaceofYichen** [osopromadze/Spring-Boot-Blog-REST-API#48]
Hi @osopromadze , thanks for replying my previous #46 ! I have yet another question: I couldn't access "GET /api/users/me" even after I signed up & signed in. (The same issue goes with "GET users/posts/etc.")

![signin](https://user-images.githubusercontent.com/50237753/147624352-301b5dc4-f1d3-4ac5-9cfc-690362bd9c86.png)

Is this supposed to work like what I did? Thanks for bearing with my naive questions!

![inq2](https://user-images.githubusercontent.com/50237753/147624357-07c36d95-9280-462e-832d-77c0a14509bc.png)

Your project is great material to learn from! Couldn't find any else that's as good as yours.

**Comment by osopromadze** [comment]
Thanks @PlaceofYichen, I am glad to hear that you find project useful for your purposes.

To access any endpoint you need to pass `Authorization` header with request, you need to put there accessToken which you get  after `signin`. 

Like in this example: 
![Image4_637468515744057981](https://user-images.githubusercontent.com/20339349/147645895-73e67ba2-6e38-48a5-b94f-f96ba850aab0.png)

Or in postman you can find authorization tab and choose there Bearer token, with this option postman will set your authorization header automatically:
![screenshot-2020-01-25-at-142816](https://user-images.githubusercontent.com/20339349/147646051-ffd5b652-22e7-4e12-855e-fa3b4665842d.png)

I hope it will help you.
