### ISSUE TITLE
Create the database via connection parameter

### ISSUE THREAD

**Issue by Throyer** [osopromadze/Spring-Boot-Blog-REST-API#49]
There is a connection parameter in mysql that creates the database
`createDatabaseIfNotExist`
```yml
    url: jdbc:mysql://blogapi-db:3306/blogapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist
```
https://github.com/osopromadze/Spring-Boot-Blog-REST-API/blob/15c7f8ed467833397d2774cbe90733bb200b6090/src/main/resources/application.yml#L3

then you can remove this step when running the application in development mode:
```sql
create database blogapi
```

**Comment by osopromadze** [comment]
Hi @Throyer, you can open PR for this issue.
